// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: agent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_Register_FullMethodName        = "/agent.AgentService/Register"
	AgentService_Heartbeat_FullMethodName       = "/agent.AgentService/Heartbeat"
	AgentService_StreamJobs_FullMethodName      = "/agent.AgentService/StreamJobs"
	AgentService_ReportJobStatus_FullMethodName = "/agent.AgentService/ReportJobStatus"
	AgentService_StreamLogs_FullMethodName      = "/agent.AgentService/StreamLogs"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService is the gRPC service implemented by the server.
//
// Architecture note: Arkeep uses a pull model — agents always initiate
// the connection to the server, never the other way around. This means
// agents can run behind NAT or firewalls without exposing any port.
//
// Typical agent lifecycle:
//  1. Agent starts and calls Register to announce itself.
//  2. Agent opens a persistent StreamJobs stream to receive job assignments.
//  3. Agent sends periodic Heartbeat calls to signal liveness and report metrics.
//  4. When a job arrives via StreamJobs, the agent executes it and calls
//     ReportJobStatus for progress updates and StreamLogs for real-time logs.
type AgentServiceClient interface {
	// Register is called once when the agent first connects or reconnects after
	// a network interruption. The server upserts the agent record in the database
	// and returns the agent's persistent UUID and display name.
	//
	// Agents should store the returned agent_id locally and reuse it on
	// subsequent Register calls so the server can match them to the existing record.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Heartbeat is called periodically by the agent (recommended interval: 30s)
	// to signal liveness and report lightweight system metrics.
	//
	// The server updates the agent's last_seen_at timestamp on every heartbeat.
	// If the server has pending jobs for this agent, it sets has_pending_jobs=true
	// in the response as a nudge — the job will arrive on the open StreamJobs stream.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// StreamJobs opens a persistent server-streaming RPC that stays alive for the
	// entire duration of the agent's session. The server pushes JobAssignment
	// messages onto this stream whenever the scheduler dispatches a job to the agent.
	//
	// The agent should reconnect with exponential backoff if the stream closes
	// unexpectedly (network drop, server restart, etc.).
	StreamJobs(ctx context.Context, in *StreamJobsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobAssignment], error)
	// ReportJobStatus is called by the agent to notify the server of job lifecycle
	// transitions: RUNNING when execution starts, then COMPLETED or FAILED when done.
	// Intermediate RUNNING calls can carry a progress message for the UI.
	ReportJobStatus(ctx context.Context, in *JobStatusReport, opts ...grpc.CallOption) (*JobStatusResponse, error)
	// StreamLogs ships log lines produced during job execution to the server in
	// real-time using client-streaming. The server buffers entries in memory and
	// flushes them to the database in bulk when the stream closes (job done).
	//
	// This avoids N individual INSERT calls during execution.
	// See server/internal/repository/job.go for the bulk insert implementation.
	StreamLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogEntry, LogStreamResponse], error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, AgentService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, AgentService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StreamJobs(ctx context.Context, in *StreamJobsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobAssignment], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_StreamJobs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamJobsRequest, JobAssignment]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StreamJobsClient = grpc.ServerStreamingClient[JobAssignment]

func (c *agentServiceClient) ReportJobStatus(ctx context.Context, in *JobStatusReport, opts ...grpc.CallOption) (*JobStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobStatusResponse)
	err := c.cc.Invoke(ctx, AgentService_ReportJobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StreamLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogEntry, LogStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[1], AgentService_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogEntry, LogStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StreamLogsClient = grpc.ClientStreamingClient[LogEntry, LogStreamResponse]

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService is the gRPC service implemented by the server.
//
// Architecture note: Arkeep uses a pull model — agents always initiate
// the connection to the server, never the other way around. This means
// agents can run behind NAT or firewalls without exposing any port.
//
// Typical agent lifecycle:
//  1. Agent starts and calls Register to announce itself.
//  2. Agent opens a persistent StreamJobs stream to receive job assignments.
//  3. Agent sends periodic Heartbeat calls to signal liveness and report metrics.
//  4. When a job arrives via StreamJobs, the agent executes it and calls
//     ReportJobStatus for progress updates and StreamLogs for real-time logs.
type AgentServiceServer interface {
	// Register is called once when the agent first connects or reconnects after
	// a network interruption. The server upserts the agent record in the database
	// and returns the agent's persistent UUID and display name.
	//
	// Agents should store the returned agent_id locally and reuse it on
	// subsequent Register calls so the server can match them to the existing record.
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Heartbeat is called periodically by the agent (recommended interval: 30s)
	// to signal liveness and report lightweight system metrics.
	//
	// The server updates the agent's last_seen_at timestamp on every heartbeat.
	// If the server has pending jobs for this agent, it sets has_pending_jobs=true
	// in the response as a nudge — the job will arrive on the open StreamJobs stream.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// StreamJobs opens a persistent server-streaming RPC that stays alive for the
	// entire duration of the agent's session. The server pushes JobAssignment
	// messages onto this stream whenever the scheduler dispatches a job to the agent.
	//
	// The agent should reconnect with exponential backoff if the stream closes
	// unexpectedly (network drop, server restart, etc.).
	StreamJobs(*StreamJobsRequest, grpc.ServerStreamingServer[JobAssignment]) error
	// ReportJobStatus is called by the agent to notify the server of job lifecycle
	// transitions: RUNNING when execution starts, then COMPLETED or FAILED when done.
	// Intermediate RUNNING calls can carry a progress message for the UI.
	ReportJobStatus(context.Context, *JobStatusReport) (*JobStatusResponse, error)
	// StreamLogs ships log lines produced during job execution to the server in
	// real-time using client-streaming. The server buffers entries in memory and
	// flushes them to the database in bulk when the stream closes (job done).
	//
	// This avoids N individual INSERT calls during execution.
	// See server/internal/repository/job.go for the bulk insert implementation.
	StreamLogs(grpc.ClientStreamingServer[LogEntry, LogStreamResponse]) error
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAgentServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedAgentServiceServer) StreamJobs(*StreamJobsRequest, grpc.ServerStreamingServer[JobAssignment]) error {
	return status.Error(codes.Unimplemented, "method StreamJobs not implemented")
}
func (UnimplementedAgentServiceServer) ReportJobStatus(context.Context, *JobStatusReport) (*JobStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportJobStatus not implemented")
}
func (UnimplementedAgentServiceServer) StreamLogs(grpc.ClientStreamingServer[LogEntry, LogStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StreamJobs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamJobsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).StreamJobs(m, &grpc.GenericServerStream[StreamJobsRequest, JobAssignment]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StreamJobsServer = grpc.ServerStreamingServer[JobAssignment]

func _AgentService_ReportJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobStatusReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportJobStatus(ctx, req.(*JobStatusReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).StreamLogs(&grpc.GenericServerStream[LogEntry, LogStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StreamLogsServer = grpc.ClientStreamingServer[LogEntry, LogStreamResponse]

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _AgentService_Register_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _AgentService_Heartbeat_Handler,
		},
		{
			MethodName: "ReportJobStatus",
			Handler:    _AgentService_ReportJobStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamJobs",
			Handler:       _AgentService_StreamJobs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamLogs",
			Handler:       _AgentService_StreamLogs_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "agent.proto",
}
