// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JobType identifies the kind of operation the agent must perform.
// The executor uses this to select the appropriate JobHandler implementation.
type JobType int32

const (
	JobType_JOB_TYPE_UNSPECIFIED JobType = 0
	// JOB_TYPE_BACKUP runs a full backup cycle: snapshot creation + optional verify.
	JobType_JOB_TYPE_BACKUP JobType = 1
	// JOB_TYPE_VERIFY checks repository integrity via restic check.
	JobType_JOB_TYPE_VERIFY JobType = 2
	// JOB_TYPE_RESTORE extracts files from a snapshot to a target directory.
	JobType_JOB_TYPE_RESTORE JobType = 3
	// JOB_TYPE_FORGET applies the retention policy via restic forget --prune.
	JobType_JOB_TYPE_FORGET JobType = 4
)

// Enum value maps for JobType.
var (
	JobType_name = map[int32]string{
		0: "JOB_TYPE_UNSPECIFIED",
		1: "JOB_TYPE_BACKUP",
		2: "JOB_TYPE_VERIFY",
		3: "JOB_TYPE_RESTORE",
		4: "JOB_TYPE_FORGET",
	}
	JobType_value = map[string]int32{
		"JOB_TYPE_UNSPECIFIED": 0,
		"JOB_TYPE_BACKUP":      1,
		"JOB_TYPE_VERIFY":      2,
		"JOB_TYPE_RESTORE":     3,
		"JOB_TYPE_FORGET":      4,
	}
)

func (x JobType) Enum() *JobType {
	p := new(JobType)
	*p = x
	return p
}

func (x JobType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobType) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (JobType) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x JobType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobType.Descriptor instead.
func (JobType) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

// JobStatus represents the lifecycle states of a job as seen by the agent.
type JobStatus int32

const (
	JobStatus_JOB_STATUS_UNSPECIFIED JobStatus = 0
	// JOB_STATUS_RUNNING is reported when the agent begins execution.
	JobStatus_JOB_STATUS_RUNNING JobStatus = 1
	// JOB_STATUS_COMPLETED is reported when the job finishes without errors.
	JobStatus_JOB_STATUS_COMPLETED JobStatus = 2
	// JOB_STATUS_FAILED is reported when the job encounters a fatal error.
	JobStatus_JOB_STATUS_FAILED JobStatus = 3
	// JOB_STATUS_CANCELLED is reported when the job is aborted (e.g. agent shutdown
	// or explicit cancellation request from the server — future feature).
	JobStatus_JOB_STATUS_CANCELLED JobStatus = 4
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNSPECIFIED",
		1: "JOB_STATUS_RUNNING",
		2: "JOB_STATUS_COMPLETED",
		3: "JOB_STATUS_FAILED",
		4: "JOB_STATUS_CANCELLED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNSPECIFIED": 0,
		"JOB_STATUS_RUNNING":     1,
		"JOB_STATUS_COMPLETED":   2,
		"JOB_STATUS_FAILED":      3,
		"JOB_STATUS_CANCELLED":   4,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[1].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[1]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

// LogLevel mirrors common logging severity levels.
// The agent maps its internal zap levels to these values before streaming.
type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_LOG_LEVEL_DEBUG       LogLevel = 1
	LogLevel_LOG_LEVEL_INFO        LogLevel = 2
	LogLevel_LOG_LEVEL_WARN        LogLevel = 3
	LogLevel_LOG_LEVEL_ERROR       LogLevel = 4
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "LOG_LEVEL_DEBUG",
		2: "LOG_LEVEL_INFO",
		3: "LOG_LEVEL_WARN",
		4: "LOG_LEVEL_ERROR",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"LOG_LEVEL_DEBUG":       1,
		"LOG_LEVEL_INFO":        2,
		"LOG_LEVEL_WARN":        3,
		"LOG_LEVEL_ERROR":       4,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[2].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[2]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

// RegisterRequest carries static information about the agent's host environment.
// This data is persisted in the agents table and displayed in the GUI.
type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// hostname as reported by the OS (os.Hostname())
	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// agent binary version in semver format (e.g. "1.2.3")
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// operating system identifier matching GOOS values: linux, windows, darwin
	Os string `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	// CPU architecture matching GOARCH values: amd64, arm64
	Arch string `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	// capabilities advertised by this agent instance — the server uses these
	// to validate that a policy assigned to this agent is actually executable
	Capabilities  *AgentCapabilities `protobuf:"bytes,5,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RegisterRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *RegisterRequest) GetCapabilities() *AgentCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// AgentCapabilities describes which optional features are available on the agent.
// Capabilities depend on the binaries installed on the host or container image.
type AgentCapabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// docker is true when the agent can reach the Docker socket and discover volumes.
	// Requires the Docker socket to be mounted (read-only) into the agent container.
	Docker bool `protobuf:"varint,1,opt,name=docker,proto3" json:"docker,omitempty"`
	// restic is true when the restic binary is found in PATH.
	// Required for all backup, verify, restore, and forget jobs.
	Restic bool `protobuf:"varint,2,opt,name=restic,proto3" json:"restic,omitempty"`
	// rclone is true when the rclone binary is found in PATH.
	// Required for destinations not natively supported by restic.
	Rclone        bool `protobuf:"varint,3,opt,name=rclone,proto3" json:"rclone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCapabilities) Reset() {
	*x = AgentCapabilities{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCapabilities) ProtoMessage() {}

func (x *AgentCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCapabilities.ProtoReflect.Descriptor instead.
func (*AgentCapabilities) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentCapabilities) GetDocker() bool {
	if x != nil {
		return x.Docker
	}
	return false
}

func (x *AgentCapabilities) GetRestic() bool {
	if x != nil {
		return x.Restic
	}
	return false
}

func (x *AgentCapabilities) GetRclone() bool {
	if x != nil {
		return x.Rclone
	}
	return false
}

// RegisterResponse contains the identity the server assigns to this agent.
// The agent must persist agent_id locally and reuse it on reconnect.
type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// agent_id is a UUIDv7 generated by the server on first registration.
	// On subsequent Register calls from the same host, the server returns
	// the existing ID rather than creating a new record.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// agent_name is the human-readable display name shown in the GUI.
	// Defaults to the hostname but can be renamed by the user.
	AgentName     string `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterResponse) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

// HeartbeatRequest is sent periodically by the agent to prove liveness
// and report current resource utilization for the monitoring dashboard.
type HeartbeatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// agent_id as returned by Register — used to identify the sender.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// metrics is a snapshot of current resource usage on the agent host.
	Metrics       *SystemMetrics `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetMetrics() *SystemMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// SystemMetrics holds a lightweight snapshot of host resource usage.
// Values are percentages to avoid unit conversion issues across platforms.
type SystemMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cpu_percent is the current CPU utilization across all cores (0–100).
	CpuPercent float32 `protobuf:"fixed32,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	// mem_percent is the percentage of physical RAM currently in use (0–100).
	MemPercent float32 `protobuf:"fixed32,2,opt,name=mem_percent,json=memPercent,proto3" json:"mem_percent,omitempty"`
	// disk_percent is the usage percentage of the primary data partition (0–100).
	// For agents running in Docker, this reflects the host partition where the
	// backup source is located, not the container overlay filesystem.
	DiskPercent   float32 `protobuf:"fixed32,3,opt,name=disk_percent,json=diskPercent,proto3" json:"disk_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemMetrics) Reset() {
	*x = SystemMetrics{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMetrics) ProtoMessage() {}

func (x *SystemMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMetrics.ProtoReflect.Descriptor instead.
func (*SystemMetrics) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *SystemMetrics) GetCpuPercent() float32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *SystemMetrics) GetMemPercent() float32 {
	if x != nil {
		return x.MemPercent
	}
	return 0
}

func (x *SystemMetrics) GetDiskPercent() float32 {
	if x != nil {
		return x.DiskPercent
	}
	return 0
}

// HeartbeatResponse acknowledges the heartbeat and carries control signals
// from the server back to the agent.
type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// has_pending_jobs is a hint that the server has jobs queued for this agent.
	// The jobs will be delivered on the open StreamJobs stream. This field exists
	// as a fallback signal in case the stream was reconnected and missed a push.
	HasPendingJobs bool `protobuf:"varint,1,opt,name=has_pending_jobs,json=hasPendingJobs,proto3" json:"has_pending_jobs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetHasPendingJobs() bool {
	if x != nil {
		return x.HasPendingJobs
	}
	return false
}

// StreamJobsRequest opens the job delivery stream for a specific agent.
type StreamJobsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// agent_id as returned by Register.
	AgentId       string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamJobsRequest) Reset() {
	*x = StreamJobsRequest{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamJobsRequest) ProtoMessage() {}

func (x *StreamJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamJobsRequest.ProtoReflect.Descriptor instead.
func (*StreamJobsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *StreamJobsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// JobAssignment is pushed by the server onto the StreamJobs stream when the
// scheduler decides a job should run on this agent.
type JobAssignment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// job_id is a UUIDv7 generated by the server when creating the job record.
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// policy_id is the UUID of the policy that triggered this job.
	// The agent uses it to fetch policy details if needed, but typically all
	// required configuration is included in the payload.
	PolicyId string `protobuf:"bytes,2,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	// type determines how the agent's executor routes the job to the correct handler.
	Type JobType `protobuf:"varint,3,opt,name=type,proto3,enum=agent.JobType" json:"type,omitempty"`
	// payload is a JSON-encoded struct whose shape depends on job type.
	// See agent/internal/executor/ for the payload structs per job type.
	// Using bytes (not string) to avoid UTF-8 validation overhead on large payloads.
	Payload []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	// scheduled_at is when the server originally scheduled this job.
	// Used for latency tracking and audit purposes.
	ScheduledAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobAssignment) Reset() {
	*x = JobAssignment{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobAssignment) ProtoMessage() {}

func (x *JobAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobAssignment.ProtoReflect.Descriptor instead.
func (*JobAssignment) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *JobAssignment) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobAssignment) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *JobAssignment) GetType() JobType {
	if x != nil {
		return x.Type
	}
	return JobType_JOB_TYPE_UNSPECIFIED
}

func (x *JobAssignment) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *JobAssignment) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

// JobStatusReport notifies the server of a lifecycle transition for a running job.
// The agent sends at least two reports per job: RUNNING at start, then COMPLETED
// or FAILED at the end. Additional RUNNING reports can carry progress messages.
type JobStatusReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// job_id must match the job_id from the JobAssignment that started this job.
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// agent_id is included for server-side validation that the reporting agent
	// is the one the job was actually assigned to.
	AgentId string `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// status is the new lifecycle state being reported.
	Status JobStatus `protobuf:"varint,3,opt,name=status,proto3,enum=agent.JobStatus" json:"status,omitempty"`
	// message is a human-readable summary of the transition.
	// Examples: "Starting backup of /var/data", "3 files added, 0 errors", "connection refused"
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// timestamp is when this status transition occurred on the agent.
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusReport) Reset() {
	*x = JobStatusReport{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusReport) ProtoMessage() {}

func (x *JobStatusReport) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusReport.ProtoReflect.Descriptor instead.
func (*JobStatusReport) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *JobStatusReport) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobStatusReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *JobStatusReport) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *JobStatusReport) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JobStatusReport) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// JobStatusResponse acknowledges receipt of the status report.
type JobStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ok is true when the server successfully persisted the status update.
	Ok            bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusResponse) Reset() {
	*x = JobStatusResponse{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusResponse) ProtoMessage() {}

func (x *JobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusResponse.ProtoReflect.Descriptor instead.
func (*JobStatusResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *JobStatusResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// LogEntry is a single log line produced by the agent during job execution.
// Entries are streamed in order and buffered server-side for bulk DB insert.
type LogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// job_id links this log entry to its parent job record.
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// agent_id is included so the server can validate the sender.
	AgentId string `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// level indicates severity, used for filtering in the GUI log viewer.
	Level LogLevel `protobuf:"varint,3,opt,name=level,proto3,enum=agent.LogLevel" json:"level,omitempty"`
	// message is the raw log line from the executor or restic wrapper.
	// Sensitive values (passwords, credentials) must be redacted by the agent
	// before including them here. See agent/internal/restic/redact.go.
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// timestamp is when the log line was produced on the agent.
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *LogEntry) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *LogEntry) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *LogEntry) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// LogStreamResponse is returned by the server when the client closes the stream.
type LogStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// entries_received is the total number of log entries the server accepted.
	// The agent can use this for basic consistency checking.
	EntriesReceived uint32 `protobuf:"varint,1,opt,name=entries_received,json=entriesReceived,proto3" json:"entries_received,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LogStreamResponse) Reset() {
	*x = LogStreamResponse{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStreamResponse) ProtoMessage() {}

func (x *LogStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStreamResponse.ProtoReflect.Descriptor instead.
func (*LogStreamResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *LogStreamResponse) GetEntriesReceived() uint32 {
	if x != nil {
		return x.EntriesReceived
	}
	return 0
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x05agent\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa9\x01\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12<\n" +
	"\fcapabilities\x18\x05 \x01(\v2\x18.agent.AgentCapabilitiesR\fcapabilities\"[\n" +
	"\x11AgentCapabilities\x12\x16\n" +
	"\x06docker\x18\x01 \x01(\bR\x06docker\x12\x16\n" +
	"\x06restic\x18\x02 \x01(\bR\x06restic\x12\x16\n" +
	"\x06rclone\x18\x03 \x01(\bR\x06rclone\"L\n" +
	"\x10RegisterResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x02 \x01(\tR\tagentName\"]\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12.\n" +
	"\ametrics\x18\x02 \x01(\v2\x14.agent.SystemMetricsR\ametrics\"t\n" +
	"\rSystemMetrics\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x02R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vmem_percent\x18\x02 \x01(\x02R\n" +
	"memPercent\x12!\n" +
	"\fdisk_percent\x18\x03 \x01(\x02R\vdiskPercent\"=\n" +
	"\x11HeartbeatResponse\x12(\n" +
	"\x10has_pending_jobs\x18\x01 \x01(\bR\x0ehasPendingJobs\".\n" +
	"\x11StreamJobsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\xc0\x01\n" +
	"\rJobAssignment\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tpolicy_id\x18\x02 \x01(\tR\bpolicyId\x12\"\n" +
	"\x04type\x18\x03 \x01(\x0e2\x0e.agent.JobTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12=\n" +
	"\fscheduled_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\"\xc1\x01\n" +
	"\x0fJobStatusReport\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12(\n" +
	"\x06status\x18\x03 \x01(\x0e2\x10.agent.JobStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"#\n" +
	"\x11JobStatusResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\xb7\x01\n" +
	"\bLogEntry\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12%\n" +
	"\x05level\x18\x03 \x01(\x0e2\x0f.agent.LogLevelR\x05level\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\">\n" +
	"\x11LogStreamResponse\x12)\n" +
	"\x10entries_received\x18\x01 \x01(\rR\x0fentriesReceived*x\n" +
	"\aJobType\x12\x18\n" +
	"\x14JOB_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fJOB_TYPE_BACKUP\x10\x01\x12\x13\n" +
	"\x0fJOB_TYPE_VERIFY\x10\x02\x12\x14\n" +
	"\x10JOB_TYPE_RESTORE\x10\x03\x12\x13\n" +
	"\x0fJOB_TYPE_FORGET\x10\x04*\x8a\x01\n" +
	"\tJobStatus\x12\x1a\n" +
	"\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12JOB_STATUS_RUNNING\x10\x01\x12\x18\n" +
	"\x14JOB_STATUS_COMPLETED\x10\x02\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x03\x12\x18\n" +
	"\x14JOB_STATUS_CANCELLED\x10\x04*w\n" +
	"\bLogLevel\x12\x19\n" +
	"\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLOG_LEVEL_DEBUG\x10\x01\x12\x12\n" +
	"\x0eLOG_LEVEL_INFO\x10\x02\x12\x12\n" +
	"\x0eLOG_LEVEL_WARN\x10\x03\x12\x13\n" +
	"\x0fLOG_LEVEL_ERROR\x10\x042\xcb\x02\n" +
	"\fAgentService\x12;\n" +
	"\bRegister\x12\x16.agent.RegisterRequest\x1a\x17.agent.RegisterResponse\x12>\n" +
	"\tHeartbeat\x12\x17.agent.HeartbeatRequest\x1a\x18.agent.HeartbeatResponse\x12>\n" +
	"\n" +
	"StreamJobs\x12\x18.agent.StreamJobsRequest\x1a\x14.agent.JobAssignment0\x01\x12C\n" +
	"\x0fReportJobStatus\x12\x16.agent.JobStatusReport\x1a\x18.agent.JobStatusResponse\x129\n" +
	"\n" +
	"StreamLogs\x12\x0f.agent.LogEntry\x1a\x18.agent.LogStreamResponse(\x01B*Z(github.com/arkeep-io/arkeep/shared/protob\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_agent_proto_goTypes = []any{
	(JobType)(0),                  // 0: agent.JobType
	(JobStatus)(0),                // 1: agent.JobStatus
	(LogLevel)(0),                 // 2: agent.LogLevel
	(*RegisterRequest)(nil),       // 3: agent.RegisterRequest
	(*AgentCapabilities)(nil),     // 4: agent.AgentCapabilities
	(*RegisterResponse)(nil),      // 5: agent.RegisterResponse
	(*HeartbeatRequest)(nil),      // 6: agent.HeartbeatRequest
	(*SystemMetrics)(nil),         // 7: agent.SystemMetrics
	(*HeartbeatResponse)(nil),     // 8: agent.HeartbeatResponse
	(*StreamJobsRequest)(nil),     // 9: agent.StreamJobsRequest
	(*JobAssignment)(nil),         // 10: agent.JobAssignment
	(*JobStatusReport)(nil),       // 11: agent.JobStatusReport
	(*JobStatusResponse)(nil),     // 12: agent.JobStatusResponse
	(*LogEntry)(nil),              // 13: agent.LogEntry
	(*LogStreamResponse)(nil),     // 14: agent.LogStreamResponse
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
}
var file_agent_proto_depIdxs = []int32{
	4,  // 0: agent.RegisterRequest.capabilities:type_name -> agent.AgentCapabilities
	7,  // 1: agent.HeartbeatRequest.metrics:type_name -> agent.SystemMetrics
	0,  // 2: agent.JobAssignment.type:type_name -> agent.JobType
	15, // 3: agent.JobAssignment.scheduled_at:type_name -> google.protobuf.Timestamp
	1,  // 4: agent.JobStatusReport.status:type_name -> agent.JobStatus
	15, // 5: agent.JobStatusReport.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 6: agent.LogEntry.level:type_name -> agent.LogLevel
	15, // 7: agent.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	3,  // 8: agent.AgentService.Register:input_type -> agent.RegisterRequest
	6,  // 9: agent.AgentService.Heartbeat:input_type -> agent.HeartbeatRequest
	9,  // 10: agent.AgentService.StreamJobs:input_type -> agent.StreamJobsRequest
	11, // 11: agent.AgentService.ReportJobStatus:input_type -> agent.JobStatusReport
	13, // 12: agent.AgentService.StreamLogs:input_type -> agent.LogEntry
	5,  // 13: agent.AgentService.Register:output_type -> agent.RegisterResponse
	8,  // 14: agent.AgentService.Heartbeat:output_type -> agent.HeartbeatResponse
	10, // 15: agent.AgentService.StreamJobs:output_type -> agent.JobAssignment
	12, // 16: agent.AgentService.ReportJobStatus:output_type -> agent.JobStatusResponse
	14, // 17: agent.AgentService.StreamLogs:output_type -> agent.LogStreamResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
