version: "3"

vars:
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
  COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "none"
  BUILD_DATE:
    sh: date -u +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || echo "unknown"
  LDFLAGS: "-s -w -X main.version={{.VERSION}} -X main.commit={{.COMMIT}} -X main.date={{.BUILD_DATE}}"

  # Versions of embedded third-party binaries.
  # Update these when you want to ship a newer restic or rclone.
  # NOTE: these vars are kept here for documentation purposes — the actual
  # version constants live in scripts/download_deps.go and must be kept in sync.
  RESTIC_VERSION: "0.18.1"
  RCLONE_VERSION: "1.73.1"

tasks:
  # ─── Build ──────────────────────────────────────────────────────────────────
  build:
    desc: Build all components
    deps: [build:server, build:agent]

  build:server:
    desc: Build server binary
    dir: server
    cmd: go build -ldflags="{{.LDFLAGS}}" -o ../bin/arkeep-server ./cmd/server

  build:agent:
    desc: Build agent binary (embeds restic + rclone — downloads them first if missing)
    deps: [deps:download]
    dir: agent
    cmd: go build -ldflags="{{.LDFLAGS}}" -o ../bin/arkeep-agent ./cmd/agent

  # ─── Embedded dependencies ──────────────────────────────────────────────────
  deps:download:
    desc: Download restic and rclone binaries for the current platform into agent/internal/restic/bin/
    # Uses a pure-Go script so that the same command works identically on
    # Linux, macOS, and Windows (cmd.exe) without requiring bash, curl,
    # bzip2, or unzip. The script is idempotent: already-present binaries
    # are skipped. To force a re-download, delete the bin/ directory first.
    cmd: go run ./scripts/download_deps.go

  deps:download:restic:
    desc: Download restic binary for the current platform (delegates to the shared Go script)
    cmd: go run ./scripts/download_deps.go

  deps:download:rclone:
    desc: Download rclone binary for the current platform (delegates to the shared Go script)
    cmd: go run ./scripts/download_deps.go

  # ─── Run (development) ──────────────────────────────────────────────────────
  run:server:
    desc: Run server in development mode
    dir: server
    cmd: go run ./cmd/server --log-level=debug
    env:
      ARKEEP_SECRET_KEY: dev-secret-key-00000000000000000
      ARKEEP_AGENT_SECRET: dev-agent-secret

  run:agent:
    desc: Run agent in development mode (downloads deps if needed)
    deps: [deps:download]
    dir: agent
    cmd: go run ./cmd/agent --server-addr=localhost:9090 --log-level=debug
    env:
      ARKEEP_AGENT_SECRET: dev-agent-secret
  
  run:gui:
    desc: Run GUI in development mode
    dir: gui
    cmd: pnpm dev

  run:dev:
    desc: Run server + GUI in development mode
    deps: [run:server, run:gui]

  # ─── Test ───────────────────────────────────────────────────────────────────
  test:
    desc: Run all tests
    deps: [test:shared, test:server, test:agent]

  test:shared:
    desc: Run shared tests
    dir: shared
    cmd: go test -v -race -count=1 ./...

  test:server:
    desc: Run server tests
    dir: server
    cmd: go test -v -race -count=1 ./...

  test:agent:
    desc: Run agent tests
    dir: agent
    cmd: go test -v -race -count=1 ./...

  # ─── Proto ──────────────────────────────────────────────────────────────────
  proto:
    desc: Generate Go code from protobuf definitions
    cmds:
      - protoc --go_out=shared/proto --go_opt=paths=source_relative --go-grpc_out=shared/proto --go-grpc_opt=paths=source_relative -I shared/proto shared/proto/agent.proto
    sources:
      - shared/proto/*.proto
    generates:
      - shared/proto/**/*.pb.go
      - shared/proto/**/*_grpc.pb.go

  # ─── Lint ───────────────────────────────────────────────────────────────────
  lint:
    desc: Run Go linter
    cmd: golangci-lint run ./...

  # ─── Tidy ───────────────────────────────────────────────────────────────────
  tidy:
    desc: Tidy all Go modules
    cmds:
      - cd shared && go mod tidy
      - cd server && go mod tidy
      - cd agent && go mod tidy

  # ─── Clean ──────────────────────────────────────────────────────────────────
  clean:
    desc: Remove build artifacts
    cmds:
      - cmd: rm -rf bin/
        ignore_error: true
        platforms: [linux, darwin]
      - cmd: cmd /c "if exist bin rmdir /s /q bin"
        ignore_error: true
        platforms: [windows]

  # ─── Seed ──────────────────────────────────────────────────────────────────
  seed:
    desc: Create a test admin user in the development database
    dir: server
    cmd: go run ./cmd/seed --email admin@test.com --password secret --name "Admin" --role admin
    env:
      ARKEEP_SECRET_KEY: dev-secret-key-00000000000000000