version: "3"

vars:
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
  COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "none"
  BUILD_DATE:
    sh: date -u +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || echo "unknown"
  LDFLAGS: "-s -w -X main.version={{.VERSION}} -X main.commit={{.COMMIT}} -X main.date={{.BUILD_DATE}}"

  # Versions of embedded third-party binaries.
  # Update these when you want to ship a newer restic or rclone.
  RESTIC_VERSION: "0.18.1"
  RCLONE_VERSION: "1.73.1"

tasks:
  # ─── Build ──────────────────────────────────────────────────────────────────
  build:
    desc: Build all components
    deps: [build:server, build:agent]

  build:server:
    desc: Build server binary
    dir: server
    cmd: go build -ldflags="{{.LDFLAGS}}" -o ../bin/arkeep-server ./cmd/server

  build:agent:
    desc: Build agent binary (embeds restic + rclone — run deps:download first)
    deps: [deps:download]
    dir: agent
    cmd: go build -ldflags="{{.LDFLAGS}}" -o ../bin/arkeep-agent ./cmd/agent

  # ─── Embedded dependencies ──────────────────────────────────────────────────
  deps:download:
    desc: Download restic and rclone binaries for the current platform into agent/internal/restic/bin/
    cmds:
      - task: deps:download:restic
      - task: deps:download:rclone

  deps:download:restic:
    desc: Download restic binary for the current platform
    vars:
      BIN_DIR: agent/internal/restic/bin
      # GoReleaser sets GOOS/GOARCH; locally they default to the host platform.
      GOOS:
        sh: go env GOOS
      GOARCH:
        sh: go env GOARCH
      RESTIC_ARCH: '{{if eq .GOARCH "amd64"}}amd64{{else if eq .GOARCH "arm64"}}arm64{{else}}{{.GOARCH}}{{end}}'
      RESTIC_OS: '{{if eq .GOOS "windows"}}windows{{else if eq .GOOS "darwin"}}darwin{{else}}linux{{end}}'
      RESTIC_EXT: '{{if eq .GOOS "windows"}}.exe{{end}}'
      RESTIC_ARCHIVE: 'restic_{{.RESTIC_VERSION}}_{{.RESTIC_OS}}_{{.RESTIC_ARCH}}.bz2'
      RESTIC_URL: 'https://github.com/restic/restic/releases/download/v{{.RESTIC_VERSION}}/{{.RESTIC_ARCHIVE}}'
      RESTIC_OUT: '{{.BIN_DIR}}/restic_{{.RESTIC_OS}}_{{.RESTIC_ARCH}}{{.RESTIC_EXT}}'
    cmds:
      - cmd: mkdir -p {{.BIN_DIR}}
        platforms: [linux, darwin]
      - cmd: if not exist {{.BIN_DIR}} mkdir {{.BIN_DIR}}
        platforms: [windows]
      # Skip download if already present (idempotent).
      - cmd: |
          if [ ! -f "{{.RESTIC_OUT}}" ]; then
            echo "Downloading restic {{.RESTIC_VERSION}} for {{.RESTIC_OS}}/{{.RESTIC_ARCH}}..."
            curl -fsSL "{{.RESTIC_URL}}" | bunzip2 > "{{.RESTIC_OUT}}"
            chmod +x "{{.RESTIC_OUT}}"
          else
            echo "restic already present: {{.RESTIC_OUT}}"
          fi
        platforms: [linux, darwin]
      - cmd: |
          if not exist "{{.RESTIC_OUT}}" (
            echo Downloading restic {{.RESTIC_VERSION}} for {{.RESTIC_OS}}/{{.RESTIC_ARCH}}...
            curl -fsSL "{{.RESTIC_URL}}" -o "{{.RESTIC_OUT}}.bz2"
            tar -xjf "{{.RESTIC_OUT}}.bz2" -C "{{.BIN_DIR}}"
            del "{{.RESTIC_OUT}}.bz2"
          ) else (
            echo restic already present: {{.RESTIC_OUT}}
          )
        platforms: [windows]

  deps:download:rclone:
    desc: Download rclone binary for the current platform
    vars:
      BIN_DIR: agent/internal/restic/bin
      GOOS:
        sh: go env GOOS
      GOARCH:
        sh: go env GOARCH
      RCLONE_ARCH: '{{if eq .GOARCH "amd64"}}amd64{{else if eq .GOARCH "arm64"}}arm64{{else}}{{.GOARCH}}{{end}}'
      RCLONE_OS: '{{if eq .GOOS "windows"}}windows{{else if eq .GOOS "darwin"}}osx{{else}}linux{{end}}'
      RCLONE_EXT: '{{if eq .GOOS "windows"}}.exe{{end}}'
      RCLONE_ARCHIVE: 'rclone-v{{.RCLONE_VERSION}}-{{.RCLONE_OS}}-{{.RCLONE_ARCH}}'
      RCLONE_URL: 'https://downloads.rclone.org/v{{.RCLONE_VERSION}}/{{.RCLONE_ARCHIVE}}.zip'
      RCLONE_OUT: '{{.BIN_DIR}}/rclone_{{.RCLONE_OS}}_{{.RCLONE_ARCH}}{{.RCLONE_EXT}}'
    cmds:
      - cmd: mkdir -p {{.BIN_DIR}}
        platforms: [linux, darwin]
      - cmd: if not exist {{.BIN_DIR}} mkdir {{.BIN_DIR}}
        platforms: [windows]
      - cmd: |
          if [ ! -f "{{.RCLONE_OUT}}" ]; then
            echo "Downloading rclone {{.RCLONE_VERSION}} for {{.RCLONE_OS}}/{{.RCLONE_ARCH}}..."
            TMP=$(mktemp -d)
            curl -fsSL "{{.RCLONE_URL}}" -o "$TMP/rclone.zip"
            unzip -j "$TMP/rclone.zip" "{{.RCLONE_ARCHIVE}}/rclone{{.RCLONE_EXT}}" -d "$TMP"
            mv "$TMP/rclone{{.RCLONE_EXT}}" "{{.RCLONE_OUT}}"
            chmod +x "{{.RCLONE_OUT}}"
            rm -rf "$TMP"
          else
            echo "rclone already present: {{.RCLONE_OUT}}"
          fi
        platforms: [linux, darwin]
      - cmd: |
          if not exist "{{.RCLONE_OUT}}" (
            echo Downloading rclone {{.RCLONE_VERSION}} for {{.RCLONE_OS}}/{{.RCLONE_ARCH}}...
            curl -fsSL "{{.RCLONE_URL}}" -o "%TEMP%\rclone.zip"
            tar -xf "%TEMP%\rclone.zip" -C "%TEMP%"
            copy "%TEMP%\{{.RCLONE_ARCHIVE}}\rclone.exe" "{{.RCLONE_OUT}}"
            rmdir /s /q "%TEMP%\{{.RCLONE_ARCHIVE}}"
            del "%TEMP%\rclone.zip"
          ) else (
            echo rclone already present: {{.RCLONE_OUT}}
          )
        platforms: [windows]

  # ─── Run (development) ──────────────────────────────────────────────────────
  run:server:
    desc: Run server in development mode
    dir: server
    cmd: go run ./cmd/server --log-level=debug
    env:
      ARKEEP_SECRET_KEY: dev-secret-key-do-not-use-in-production

  run:agent:
    desc: Run agent in development mode (downloads deps if needed)
    deps: [deps:download]
    dir: agent
    cmd: go run ./cmd/agent --server-addr=localhost:9090 --log-level=debug
    env:
      ARKEEP_AGENT_TOKEN: dev-token

  # ─── Test ───────────────────────────────────────────────────────────────────
  test:
    desc: Run all tests
    deps: [test:shared, test:server, test:agent]

  test:shared:
    desc: Run shared tests
    dir: shared
    cmd: go test -v -race -count=1 ./...

  test:server:
    desc: Run server tests
    dir: server
    cmd: go test -v -race -count=1 ./...

  test:agent:
    desc: Run agent tests
    dir: agent
    cmd: go test -v -race -count=1 ./...

  # ─── Proto ──────────────────────────────────────────────────────────────────
  proto:
    desc: Generate Go code from protobuf definitions
    cmds:
      - protoc --go_out=shared/proto --go_opt=paths=source_relative --go-grpc_out=shared/proto --go-grpc_opt=paths=source_relative -I shared/proto shared/proto/agent.proto
    sources:
      - shared/proto/*.proto
    generates:
      - shared/proto/**/*.pb.go
      - shared/proto/**/*_grpc.pb.go

  # ─── Lint ───────────────────────────────────────────────────────────────────
  lint:
    desc: Run Go linter
    cmd: golangci-lint run ./...

  # ─── Tidy ───────────────────────────────────────────────────────────────────
  tidy:
    desc: Tidy all Go modules
    cmds:
      - cd shared && go mod tidy
      - cd server && go mod tidy
      - cd agent && go mod tidy

  # ─── Clean ──────────────────────────────────────────────────────────────────
  clean:
    desc: Remove build artifacts
    cmds:
      - cmd: rm -rf bin/
        ignore_error: true
        platforms: [linux, darwin]
      - cmd: if exist bin rmdir /s /q bin
        ignore_error: true
        platforms: [windows]