package api

import (
	"crypto/subtle"
	"encoding/json"
	"net"
	"net/http"
	"time"

	"github.com/google/uuid"
	"go.uber.org/zap"

	grpccerts "github.com/arkeep-io/arkeep/server/internal/grpc"
)

// maxEnrollBodyBytes caps the enrollment request: a secret and a CSR fit in
// a few KiB.
const maxEnrollBodyBytes = 64 << 10

// EnrollHandler handles agent enrollment requests.
// Agents call POST /api/v1/agents/enroll to obtain a CA certificate and a
// signed client certificate that they then use for mTLS on the gRPC port.
type EnrollHandler struct {
	autoCerts   *grpccerts.AutoCerts
	agentSecret string
	logger      *zap.Logger
	rateLimiter *RateLimiter
}

// NewEnrollHandler creates a new EnrollHandler.
// agentSecret is the shared bootstrap secret agents must present to enroll.
func NewEnrollHandler(autoCerts *grpccerts.AutoCerts, agentSecret string, logger *zap.Logger) *EnrollHandler {
	return &EnrollHandler{
		autoCerts:   autoCerts,
		agentSecret: agentSecret,
		logger:      logger.Named("enroll_handler"),
		rateLimiter: NewRateLimiter(10, time.Minute),
	}
}

// Enroll handles POST /api/v1/agents/enroll.
func (h *EnrollHandler) Enroll(w http.ResponseWriter, r *http.Request) {
	// Rate limiting
	ip := clientIP(r)
	if !h.rateLimiter.Allow(ip) {
		w.Header().Set("Retry-After", "60")
		http.Error(w, "rate limit exceeded — max 10 enrollment requests per minute per IP", http.StatusTooManyRequests)
		return
	}

	var body struct {
		AgentSecret string `json:"agent_secret"`
		// CSR is the agent's PEM certificate signing request. Agents older
		// than 0.9 send none and get a server-generated key instead.
		CSR string `json:"csr"`
	}
	r.Body = http.MaxBytesReader(w, r.Body, maxEnrollBodyBytes)
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		http.Error(w, "invalid JSON body", http.StatusBadRequest)
		return
	}

	// An empty configured secret fails closed (the server refuses to start
	// without one), and the comparison is constant-time.
	if h.agentSecret == "" || subtle.ConstantTimeCompare([]byte(body.AgentSecret), []byte(h.agentSecret)) != 1 {
		h.logger.Warn("enrollment rejected: wrong agent_secret", zap.String("ip", ip))
		http.Error(w, "forbidden", http.StatusForbidden)
		return
	}

	// Issue a per-agent client certificate. The CN embeds a UUID so each
	// enrolled agent gets a unique certificate even if enrolled multiple times.
	cn := "arkeep-agent-" + uuid.New().String()
	resp := map[string]string{"ca_cert": string(h.autoCerts.CACertPEM)}

	if body.CSR != "" {
		// The agent keeps its private key: only the signed certificate is sent.
		certPEM, err := h.autoCerts.SignCSR([]byte(body.CSR), cn)
		if err != nil {
			h.logger.Warn("enrollment rejected: invalid csr", zap.String("ip", ip), zap.Error(err))
			http.Error(w, "invalid csr", http.StatusBadRequest)
			return
		}
		resp["client_cert"] = string(certPEM)
	} else {
		certPEM, keyPEM, err := h.autoCerts.IssueCertificate(cn)
		if err != nil {
			h.logger.Error("failed to issue client certificate", zap.Error(err))
			http.Error(w, "internal server error", http.StatusInternalServerError)
			return
		}
		h.logger.Warn("agent enrolled without a csr: its private key was generated by the server and sent over the network; upgrade the agent",
			zap.String("ip", ip),
		)
		resp["client_cert"] = string(certPEM)
		resp["client_key"] = string(keyPEM)
	}

	h.logger.Info("agent enrolled", zap.String("cn", cn), zap.String("ip", ip), zap.Bool("csr", body.CSR != ""))

	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(resp)
}

// clientIP extracts the real client IP from the request, preferring the value
// set by middleware.RealIP (stored in RemoteAddr after chi processes it).
func clientIP(r *http.Request) string {
	host, _, err := net.SplitHostPort(r.RemoteAddr)
	if err != nil {
		return r.RemoteAddr
	}
	return host
}
